main: org.zkaleejoo.SimpleAds
name: SimpleAds
version: ${project.version}
author: ZkAleeJoo
api-version: 1.19
softdepend: [PlaceholderAPI]

commands:
  ads:
    description: Comando principal de SimpleAds
    usage: /ads

permissions:
  simpleads.use:
    description: Permissions for the /ads command
    default: op


