main: org.zkaleejoo.SimpleAds
name: SimpleAds
version: 1.0.3
author: ZkAleeJoo
api-version: 1.20

commands:
  ads:
    description: Comando principal de SimpleAds
    usage: /ads

permissions:
  simpleads.use:
    description: Permissions for the /ads command
    default: op


